### ISSUE TITLE
module 'packer' not found

### ISSUE THREAD

**Issue by namanUIUC** [smithbm2316/vimconf-2021#3]
Inspired by your advanced lua configuration, I decided to replace everything in my `./.config/nvim/` with what you have in "lua_advanced_setup". 

Then I installed packer for the first time (switching from vundle)
```
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
```

I thought this should be enough to get started. But unfortunately I ran into this error:
```
Error detected while processing /Users/namanshukla/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/namanshukla/.config/nvim/lua/plugins.lua:1: module 'packer' not found:
        no field package.preload['packer']
        no file './packer.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/luajit-2.1.0-beta3/packer.lua'
        no file '/usr/local/share/lua/5.1/packer.lua'
        no file '/usr/local/share/lua/5.1/packer/init.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/packer.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/packer/init.lua'
        no file './packer.so'
        no file '/usr/local/lib/lua/5.1/packer.so'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/lib/lua/5.1/packer.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /Users/namanshukla/.config/nvim/lua/plugins.lua:1: in main chunk
        [C]: in function 'require'
        /Users/namanshukla/.config/nvim/init.lua:10: in main chunk
Press ENTER or type command to continue
```

I am using:

- Operating system/version: macOS Monterey 12.0.1
- Terminal Emulator: iTerm2
- Neovim: 
```
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey
```

**Comment by smithbm2316** [comment]
Hey @namanUIUC! Thanks for checking out the repo. I had totally forgotten to add a very crucial step to the `lua_advanced_config`, my apologies! I just pushed a new commit to the repo, if you copy the current `lua_advanced_config/init.lua` over to your personal configuration, it should work now!

Basically, we need to install `packer.nvim` using `git clone` before we use it as a package manager (if you didn't know, package managers for Vim/Neovim basically are just wrappers around `git clone` with other nice features on top of it). The extra several lines of code that I added to the top of `init.lua` goes ahead and installs it to your User data directory (you can check `:help stdpath()` in Vim for more info on this). That snippet is taken pretty much directly from `packer.nvim`'s README itself, if you want to take a look at what they recommend for installing. Let me know if you have any other questions!

**Comment by namanUIUC** [comment]
Thanks. This works! 💯 
Closing this issue
